### ISSUE TITLE
Version incompatibility

### ISSUE THREAD

**Issue by czpmango** [wey-gu/vscode-ngql#1]
Could you provide a version support list, there was an error when I install this plugin.
```
安装 "nGQL" 扩展时出错。
无法安装“wey-gu.vscode-ngql”扩展，因为它与 VS Code 的当前版本(版本 1.52.1)不兼容。
```

**Comment by wey-gu** [comment]
Thank you @czpmango, will work on that, it should be supported for slightly older versions as there aren't too many dependencies underlying actually, just the latest version was specified as the lowest supported version.

Sorry for this, will release a newer version with a lower version requirement.

**Comment by wey-gu** [comment]
@czpmango , would you mind try to install the latest published version to see if it's allowed to be installed on `1.52.1`?

Now it's claimed to support a version back to `1.50.1`, which is from Sept. 2020.

Thanks!!!

**Comment by czpmango** [comment]
It has worked. Good job~

**Comment by wey-gu** [comment]
> It has worked. Good job~

Got it Kyle, thanks!
